<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Seguro', 'doctrine');

/**
 * BaseSeguro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $seguro_tipo_id
 * @property integer $seguro_plan_id
 * @property string $nombre
 * @property integer $dia
 * @property string $descripcion
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property SeguroTipo $SeguroTipo
 * @property SeguroPlan $SeguroPlan
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $SeguroHasBeneficio
 * @property Doctrine_Collection $SeguroPrecio
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getEmpresaId()          Returns the current record's "empresa_id" value
 * @method integer             getSeguroTipoId()       Returns the current record's "seguro_tipo_id" value
 * @method integer             getSeguroPlanId()       Returns the current record's "seguro_plan_id" value
 * @method string              getNombre()             Returns the current record's "nombre" value
 * @method integer             getDia()                Returns the current record's "dia" value
 * @method string              getDescripcion()        Returns the current record's "descripcion" value
 * @method integer             getUserId()             Returns the current record's "user_id" value
 * @method string              getUserName()           Returns the current record's "user_name" value
 * @method Empresa             getEmpresa()            Returns the current record's "Empresa" value
 * @method SeguroTipo          getSeguroTipo()         Returns the current record's "SeguroTipo" value
 * @method SeguroPlan          getSeguroPlan()         Returns the current record's "SeguroPlan" value
 * @method sfGuardUser         getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getSeguroHasBeneficio() Returns the current record's "SeguroHasBeneficio" collection
 * @method Doctrine_Collection getSeguroPrecio()       Returns the current record's "SeguroPrecio" collection
 * @method Seguro              setId()                 Sets the current record's "id" value
 * @method Seguro              setEmpresaId()          Sets the current record's "empresa_id" value
 * @method Seguro              setSeguroTipoId()       Sets the current record's "seguro_tipo_id" value
 * @method Seguro              setSeguroPlanId()       Sets the current record's "seguro_plan_id" value
 * @method Seguro              setNombre()             Sets the current record's "nombre" value
 * @method Seguro              setDia()                Sets the current record's "dia" value
 * @method Seguro              setDescripcion()        Sets the current record's "descripcion" value
 * @method Seguro              setUserId()             Sets the current record's "user_id" value
 * @method Seguro              setUserName()           Sets the current record's "user_name" value
 * @method Seguro              setEmpresa()            Sets the current record's "Empresa" value
 * @method Seguro              setSeguroTipo()         Sets the current record's "SeguroTipo" value
 * @method Seguro              setSeguroPlan()         Sets the current record's "SeguroPlan" value
 * @method Seguro              setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * @method Seguro              setSeguroHasBeneficio() Sets the current record's "SeguroHasBeneficio" collection
 * @method Seguro              setSeguroPrecio()       Sets the current record's "SeguroPrecio" collection
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeguro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seguro');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 1,
             'autoincrement' => false,
             ));
        $this->hasColumn('seguro_tipo_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('seguro_plan_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('dia', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('SeguroTipo', array(
             'local' => 'seguro_tipo_id',
             'foreign' => 'id'));

        $this->hasOne('SeguroPlan', array(
             'local' => 'seguro_plan_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('SeguroHasBeneficio', array(
             'local' => 'id',
             'foreign' => 'seguro_id'));

        $this->hasMany('SeguroPrecio', array(
             'local' => 'id',
             'foreign' => 'seguro_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}