<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServicioBitacora', 'doctrine');

/**
 * BaseServicioBitacora
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $agendado_bitacora_id
 * @property integer $servicio_tipo_id
 * @property integer $categoria_id
 * @property integer $producto_id
 * @property integer $servicio_status_id
 * @property integer $tamano_id
 * @property string $presentacion_id
 * @property string $codigo
 * @property integer $cantidad
 * @property string $nota
 * @property float $precio
 * @property float $impuestos
 * @property integer $puntos
 * @property AgendadoBitacora $AgendadoBitacora
 * @property Producto $Producto
 * @property ServicioStatus $ServicioStatus
 * @property Doctrine_Collection $MascotaHasServicioBitacora
 * 
 * @method integer             getId()                         Returns the current record's "id" value
 * @method integer             getAgendadoBitacoraId()         Returns the current record's "agendado_bitacora_id" value
 * @method integer             getServicioTipoId()             Returns the current record's "servicio_tipo_id" value
 * @method integer             getCategoriaId()                Returns the current record's "categoria_id" value
 * @method integer             getProductoId()                 Returns the current record's "producto_id" value
 * @method integer             getServicioStatusId()           Returns the current record's "servicio_status_id" value
 * @method integer             getTamanoId()                   Returns the current record's "tamano_id" value
 * @method string              getPresentacionId()             Returns the current record's "presentacion_id" value
 * @method string              getCodigo()                     Returns the current record's "codigo" value
 * @method integer             getCantidad()                   Returns the current record's "cantidad" value
 * @method string              getNota()                       Returns the current record's "nota" value
 * @method float               getPrecio()                     Returns the current record's "precio" value
 * @method float               getImpuestos()                  Returns the current record's "impuestos" value
 * @method integer             getPuntos()                     Returns the current record's "puntos" value
 * @method AgendadoBitacora    getAgendadoBitacora()           Returns the current record's "AgendadoBitacora" value
 * @method Producto            getProducto()                   Returns the current record's "Producto" value
 * @method ServicioStatus      getServicioStatus()             Returns the current record's "ServicioStatus" value
 * @method Doctrine_Collection getMascotaHasServicioBitacora() Returns the current record's "MascotaHasServicioBitacora" collection
 * @method ServicioBitacora    setId()                         Sets the current record's "id" value
 * @method ServicioBitacora    setAgendadoBitacoraId()         Sets the current record's "agendado_bitacora_id" value
 * @method ServicioBitacora    setServicioTipoId()             Sets the current record's "servicio_tipo_id" value
 * @method ServicioBitacora    setCategoriaId()                Sets the current record's "categoria_id" value
 * @method ServicioBitacora    setProductoId()                 Sets the current record's "producto_id" value
 * @method ServicioBitacora    setServicioStatusId()           Sets the current record's "servicio_status_id" value
 * @method ServicioBitacora    setTamanoId()                   Sets the current record's "tamano_id" value
 * @method ServicioBitacora    setPresentacionId()             Sets the current record's "presentacion_id" value
 * @method ServicioBitacora    setCodigo()                     Sets the current record's "codigo" value
 * @method ServicioBitacora    setCantidad()                   Sets the current record's "cantidad" value
 * @method ServicioBitacora    setNota()                       Sets the current record's "nota" value
 * @method ServicioBitacora    setPrecio()                     Sets the current record's "precio" value
 * @method ServicioBitacora    setImpuestos()                  Sets the current record's "impuestos" value
 * @method ServicioBitacora    setPuntos()                     Sets the current record's "puntos" value
 * @method ServicioBitacora    setAgendadoBitacora()           Sets the current record's "AgendadoBitacora" value
 * @method ServicioBitacora    setProducto()                   Sets the current record's "Producto" value
 * @method ServicioBitacora    setServicioStatus()             Sets the current record's "ServicioStatus" value
 * @method ServicioBitacora    setMascotaHasServicioBitacora() Sets the current record's "MascotaHasServicioBitacora" collection
 * 
 * @package    cronos-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicioBitacora extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicio_bitacora');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('agendado_bitacora_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('servicio_tipo_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('categoria_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('servicio_status_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('tamano_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('presentacion_id', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('codigo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('cantidad', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('nota', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('precio', 'float', 16, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('impuestos', 'float', 16, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('puntos', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AgendadoBitacora', array(
             'local' => 'agendado_bitacora_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('ServicioStatus', array(
             'local' => 'servicio_status_id',
             'foreign' => 'id'));

        $this->hasMany('MascotaHasServicioBitacora', array(
             'local' => 'id',
             'foreign' => 'servicio_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}