<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VehiculoMarcaModelo', 'doctrine');

/**
 * BaseVehiculoMarcaModelo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $vehiculo_marca_id
 * @property string $nombre
 * @property string $descripcion
 * @property integer $status
 * @property integer $cantidad_puerta
 * @property integer $capacidad_maleta
 * @property integer $capacidad_persona
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property VehiculoMarca $VehiculoMarca
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $Vehiculo
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getEmpresaId()         Returns the current record's "empresa_id" value
 * @method integer             getVehiculoMarcaId()   Returns the current record's "vehiculo_marca_id" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method string              getDescripcion()       Returns the current record's "descripcion" value
 * @method integer             getStatus()            Returns the current record's "status" value
 * @method integer             getCantidadPuerta()    Returns the current record's "cantidad_puerta" value
 * @method integer             getCapacidadMaleta()   Returns the current record's "capacidad_maleta" value
 * @method integer             getCapacidadPersona()  Returns the current record's "capacidad_persona" value
 * @method integer             getUserId()            Returns the current record's "user_id" value
 * @method string              getUserName()          Returns the current record's "user_name" value
 * @method Empresa             getEmpresa()           Returns the current record's "Empresa" value
 * @method VehiculoMarca       getVehiculoMarca()     Returns the current record's "VehiculoMarca" value
 * @method sfGuardUser         getSfGuardUser()       Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getVehiculo()          Returns the current record's "Vehiculo" collection
 * @method VehiculoMarcaModelo setId()                Sets the current record's "id" value
 * @method VehiculoMarcaModelo setEmpresaId()         Sets the current record's "empresa_id" value
 * @method VehiculoMarcaModelo setVehiculoMarcaId()   Sets the current record's "vehiculo_marca_id" value
 * @method VehiculoMarcaModelo setNombre()            Sets the current record's "nombre" value
 * @method VehiculoMarcaModelo setDescripcion()       Sets the current record's "descripcion" value
 * @method VehiculoMarcaModelo setStatus()            Sets the current record's "status" value
 * @method VehiculoMarcaModelo setCantidadPuerta()    Sets the current record's "cantidad_puerta" value
 * @method VehiculoMarcaModelo setCapacidadMaleta()   Sets the current record's "capacidad_maleta" value
 * @method VehiculoMarcaModelo setCapacidadPersona()  Sets the current record's "capacidad_persona" value
 * @method VehiculoMarcaModelo setUserId()            Sets the current record's "user_id" value
 * @method VehiculoMarcaModelo setUserName()          Sets the current record's "user_name" value
 * @method VehiculoMarcaModelo setEmpresa()           Sets the current record's "Empresa" value
 * @method VehiculoMarcaModelo setVehiculoMarca()     Sets the current record's "VehiculoMarca" value
 * @method VehiculoMarcaModelo setSfGuardUser()       Sets the current record's "sfGuardUser" value
 * @method VehiculoMarcaModelo setVehiculo()          Sets the current record's "Vehiculo" collection
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehiculoMarcaModelo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehiculo_marca_modelo');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 1,
             'autoincrement' => false,
             ));
        $this->hasColumn('vehiculo_marca_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 1,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('cantidad_puerta', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('capacidad_maleta', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('capacidad_persona', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('VehiculoMarca', array(
             'local' => 'vehiculo_marca_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Vehiculo', array(
             'local' => 'id',
             'foreign' => 'vehiculo_marca_modelo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}