<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rede', 'doctrine');

/**
 * BaseRede
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property string $nombre
 * @property string $logo
 * @property integer $user_id
 * @property string $user_name
 * @property integer $status
 * @property Empresa $Empresa
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $ProveedorRede
 * @property Doctrine_Collection $HospedajeRede
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getEmpresaId()     Returns the current record's "empresa_id" value
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method string              getLogo()          Returns the current record's "logo" value
 * @method integer             getUserId()        Returns the current record's "user_id" value
 * @method string              getUserName()      Returns the current record's "user_name" value
 * @method integer             getStatus()        Returns the current record's "status" value
 * @method Empresa             getEmpresa()       Returns the current record's "Empresa" value
 * @method sfGuardUser         getSfGuardUser()   Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getProveedorRede() Returns the current record's "ProveedorRede" collection
 * @method Doctrine_Collection getHospedajeRede() Returns the current record's "HospedajeRede" collection
 * @method Rede                setId()            Sets the current record's "id" value
 * @method Rede                setEmpresaId()     Sets the current record's "empresa_id" value
 * @method Rede                setNombre()        Sets the current record's "nombre" value
 * @method Rede                setLogo()          Sets the current record's "logo" value
 * @method Rede                setUserId()        Sets the current record's "user_id" value
 * @method Rede                setUserName()      Sets the current record's "user_name" value
 * @method Rede                setStatus()        Sets the current record's "status" value
 * @method Rede                setEmpresa()       Sets the current record's "Empresa" value
 * @method Rede                setSfGuardUser()   Sets the current record's "sfGuardUser" value
 * @method Rede                setProveedorRede() Sets the current record's "ProveedorRede" collection
 * @method Rede                setHospedajeRede() Sets the current record's "HospedajeRede" collection
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRede extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rede');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('logo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('ProveedorRede', array(
             'local' => 'id',
             'foreign' => 'rede_id'));

        $this->hasMany('HospedajeRede', array(
             'local' => 'id',
             'foreign' => 'rede_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}