<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VehiculoHasPolitica', 'doctrine');

/**
 * BaseVehiculoHasPolitica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $vehiculo_id
 * @property integer $vehiculo_politica_id
 * @property integer $valor
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property Vehiculo $Vehiculo
 * @property VehiculoPolitica $VehiculoPolitica
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method integer             getEmpresaId()            Returns the current record's "empresa_id" value
 * @method integer             getVehiculoId()           Returns the current record's "vehiculo_id" value
 * @method integer             getVehiculoPoliticaId()   Returns the current record's "vehiculo_politica_id" value
 * @method integer             getValor()                Returns the current record's "valor" value
 * @method integer             getUserId()               Returns the current record's "user_id" value
 * @method string              getUserName()             Returns the current record's "user_name" value
 * @method Empresa             getEmpresa()              Returns the current record's "Empresa" value
 * @method Vehiculo            getVehiculo()             Returns the current record's "Vehiculo" value
 * @method VehiculoPolitica    getVehiculoPolitica()     Returns the current record's "VehiculoPolitica" value
 * @method sfGuardUser         getSfGuardUser()          Returns the current record's "sfGuardUser" value
 * @method VehiculoHasPolitica setId()                   Sets the current record's "id" value
 * @method VehiculoHasPolitica setEmpresaId()            Sets the current record's "empresa_id" value
 * @method VehiculoHasPolitica setVehiculoId()           Sets the current record's "vehiculo_id" value
 * @method VehiculoHasPolitica setVehiculoPoliticaId()   Sets the current record's "vehiculo_politica_id" value
 * @method VehiculoHasPolitica setValor()                Sets the current record's "valor" value
 * @method VehiculoHasPolitica setUserId()               Sets the current record's "user_id" value
 * @method VehiculoHasPolitica setUserName()             Sets the current record's "user_name" value
 * @method VehiculoHasPolitica setEmpresa()              Sets the current record's "Empresa" value
 * @method VehiculoHasPolitica setVehiculo()             Sets the current record's "Vehiculo" value
 * @method VehiculoHasPolitica setVehiculoPolitica()     Sets the current record's "VehiculoPolitica" value
 * @method VehiculoHasPolitica setSfGuardUser()          Sets the current record's "sfGuardUser" value
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehiculoHasPolitica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehiculo_has_politica');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('vehiculo_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('vehiculo_politica_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('valor', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Vehiculo', array(
             'local' => 'vehiculo_id',
             'foreign' => 'id'));

        $this->hasOne('VehiculoPolitica', array(
             'local' => 'vehiculo_politica_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}