<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HospedajeRede', 'doctrine');

/**
 * BaseHospedajeRede
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $hospedaje_id
 * @property integer $rede_id
 * @property string $direccion
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property Hospedaje $Hospedaje
 * @property Rede $Rede
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getEmpresaId()    Returns the current record's "empresa_id" value
 * @method integer       getHospedajeId()  Returns the current record's "hospedaje_id" value
 * @method integer       getRedeId()       Returns the current record's "rede_id" value
 * @method string        getDireccion()    Returns the current record's "direccion" value
 * @method integer       getUserId()       Returns the current record's "user_id" value
 * @method string        getUserName()     Returns the current record's "user_name" value
 * @method Empresa       getEmpresa()      Returns the current record's "Empresa" value
 * @method Hospedaje     getHospedaje()    Returns the current record's "Hospedaje" value
 * @method Rede          getRede()         Returns the current record's "Rede" value
 * @method sfGuardUser   getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method HospedajeRede setId()           Sets the current record's "id" value
 * @method HospedajeRede setEmpresaId()    Sets the current record's "empresa_id" value
 * @method HospedajeRede setHospedajeId()  Sets the current record's "hospedaje_id" value
 * @method HospedajeRede setRedeId()       Sets the current record's "rede_id" value
 * @method HospedajeRede setDireccion()    Sets the current record's "direccion" value
 * @method HospedajeRede setUserId()       Sets the current record's "user_id" value
 * @method HospedajeRede setUserName()     Sets the current record's "user_name" value
 * @method HospedajeRede setEmpresa()      Sets the current record's "Empresa" value
 * @method HospedajeRede setHospedaje()    Sets the current record's "Hospedaje" value
 * @method HospedajeRede setRede()         Sets the current record's "Rede" value
 * @method HospedajeRede setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHospedajeRede extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hospedaje_rede');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('hospedaje_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('rede_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Hospedaje', array(
             'local' => 'hospedaje_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Rede', array(
             'local' => 'rede_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}