<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GaleriaProveedor', 'doctrine');

/**
 * BaseGaleriaProveedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $proveedor_id
 * @property string $imagen
 * @property string $descripcion
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property Proveedor $Proveedor
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer          getId()           Returns the current record's "id" value
 * @method integer          getEmpresaId()    Returns the current record's "empresa_id" value
 * @method integer          getProveedorId()  Returns the current record's "proveedor_id" value
 * @method string           getImagen()       Returns the current record's "imagen" value
 * @method string           getDescripcion()  Returns the current record's "descripcion" value
 * @method integer          getUserId()       Returns the current record's "user_id" value
 * @method string           getUserName()     Returns the current record's "user_name" value
 * @method Empresa          getEmpresa()      Returns the current record's "Empresa" value
 * @method Proveedor        getProveedor()    Returns the current record's "Proveedor" value
 * @method sfGuardUser      getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method GaleriaProveedor setId()           Sets the current record's "id" value
 * @method GaleriaProveedor setEmpresaId()    Sets the current record's "empresa_id" value
 * @method GaleriaProveedor setProveedorId()  Sets the current record's "proveedor_id" value
 * @method GaleriaProveedor setImagen()       Sets the current record's "imagen" value
 * @method GaleriaProveedor setDescripcion()  Sets the current record's "descripcion" value
 * @method GaleriaProveedor setUserId()       Sets the current record's "user_id" value
 * @method GaleriaProveedor setUserName()     Sets the current record's "user_name" value
 * @method GaleriaProveedor setEmpresa()      Sets the current record's "Empresa" value
 * @method GaleriaProveedor setProveedor()    Sets the current record's "Proveedor" value
 * @method GaleriaProveedor setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGaleriaProveedor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('galeria_proveedor');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('proveedor_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('imagen', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Proveedor', array(
             'local' => 'proveedor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}