<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VehiculoHasSeguro', 'doctrine');

/**
 * BaseVehiculoHasSeguro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $vehiculo_id
 * @property integer $vehiculo_seguro_id
 * @property integer $valor
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property Vehiculo $Vehiculo
 * @property VehiculoSeguro $VehiculoSeguro
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer           getId()                 Returns the current record's "id" value
 * @method integer           getEmpresaId()          Returns the current record's "empresa_id" value
 * @method integer           getVehiculoId()         Returns the current record's "vehiculo_id" value
 * @method integer           getVehiculoSeguroId()   Returns the current record's "vehiculo_seguro_id" value
 * @method integer           getValor()              Returns the current record's "valor" value
 * @method integer           getUserId()             Returns the current record's "user_id" value
 * @method string            getUserName()           Returns the current record's "user_name" value
 * @method Empresa           getEmpresa()            Returns the current record's "Empresa" value
 * @method Vehiculo          getVehiculo()           Returns the current record's "Vehiculo" value
 * @method VehiculoSeguro    getVehiculoSeguro()     Returns the current record's "VehiculoSeguro" value
 * @method sfGuardUser       getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method VehiculoHasSeguro setId()                 Sets the current record's "id" value
 * @method VehiculoHasSeguro setEmpresaId()          Sets the current record's "empresa_id" value
 * @method VehiculoHasSeguro setVehiculoId()         Sets the current record's "vehiculo_id" value
 * @method VehiculoHasSeguro setVehiculoSeguroId()   Sets the current record's "vehiculo_seguro_id" value
 * @method VehiculoHasSeguro setValor()              Sets the current record's "valor" value
 * @method VehiculoHasSeguro setUserId()             Sets the current record's "user_id" value
 * @method VehiculoHasSeguro setUserName()           Sets the current record's "user_name" value
 * @method VehiculoHasSeguro setEmpresa()            Sets the current record's "Empresa" value
 * @method VehiculoHasSeguro setVehiculo()           Sets the current record's "Vehiculo" value
 * @method VehiculoHasSeguro setVehiculoSeguro()     Sets the current record's "VehiculoSeguro" value
 * @method VehiculoHasSeguro setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehiculoHasSeguro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehiculo_has_seguro');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 1,
             'autoincrement' => false,
             ));
        $this->hasColumn('vehiculo_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('vehiculo_seguro_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('valor', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Vehiculo', array(
             'local' => 'vehiculo_id',
             'foreign' => 'id'));

        $this->hasOne('VehiculoSeguro', array(
             'local' => 'vehiculo_seguro_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}