<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RangoEdad', 'doctrine');

/**
 * BaseRangoEdad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property string $nombre
 * @property string $descripcion
 * @property integer $rango_desde
 * @property integer $rango_hasta
 * @property integer $status
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $TipoTarifaPrecio
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getEmpresaId()        Returns the current record's "empresa_id" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getDescripcion()      Returns the current record's "descripcion" value
 * @method integer             getRangoDesde()       Returns the current record's "rango_desde" value
 * @method integer             getRangoHasta()       Returns the current record's "rango_hasta" value
 * @method integer             getStatus()           Returns the current record's "status" value
 * @method integer             getUserId()           Returns the current record's "user_id" value
 * @method string              getUserName()         Returns the current record's "user_name" value
 * @method Empresa             getEmpresa()          Returns the current record's "Empresa" value
 * @method sfGuardUser         getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getTipoTarifaPrecio() Returns the current record's "TipoTarifaPrecio" collection
 * @method RangoEdad           setId()               Sets the current record's "id" value
 * @method RangoEdad           setEmpresaId()        Sets the current record's "empresa_id" value
 * @method RangoEdad           setNombre()           Sets the current record's "nombre" value
 * @method RangoEdad           setDescripcion()      Sets the current record's "descripcion" value
 * @method RangoEdad           setRangoDesde()       Sets the current record's "rango_desde" value
 * @method RangoEdad           setRangoHasta()       Sets the current record's "rango_hasta" value
 * @method RangoEdad           setStatus()           Sets the current record's "status" value
 * @method RangoEdad           setUserId()           Sets the current record's "user_id" value
 * @method RangoEdad           setUserName()         Sets the current record's "user_name" value
 * @method RangoEdad           setEmpresa()          Sets the current record's "Empresa" value
 * @method RangoEdad           setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * @method RangoEdad           setTipoTarifaPrecio() Sets the current record's "TipoTarifaPrecio" collection
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRangoEdad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rango_edad');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('rango_desde', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('rango_hasta', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('TipoTarifaPrecio', array(
             'local' => 'id',
             'foreign' => 'rango_edad_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}