<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoCliente', 'doctrine');

/**
 * BaseTipoCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property string $nombre
 * @property string $descripcion
 * @property string $orden
 * @property string $imagen
 * @property integer $status
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $Cliente
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getEmpresaId()   Returns the current record's "empresa_id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method string              getOrden()       Returns the current record's "orden" value
 * @method string              getImagen()      Returns the current record's "imagen" value
 * @method integer             getStatus()      Returns the current record's "status" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method string              getUserName()    Returns the current record's "user_name" value
 * @method Empresa             getEmpresa()     Returns the current record's "Empresa" value
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getCliente()     Returns the current record's "Cliente" collection
 * @method TipoCliente         setId()          Sets the current record's "id" value
 * @method TipoCliente         setEmpresaId()   Sets the current record's "empresa_id" value
 * @method TipoCliente         setNombre()      Sets the current record's "nombre" value
 * @method TipoCliente         setDescripcion() Sets the current record's "descripcion" value
 * @method TipoCliente         setOrden()       Sets the current record's "orden" value
 * @method TipoCliente         setImagen()      Sets the current record's "imagen" value
 * @method TipoCliente         setStatus()      Sets the current record's "status" value
 * @method TipoCliente         setUserId()      Sets the current record's "user_id" value
 * @method TipoCliente         setUserName()    Sets the current record's "user_name" value
 * @method TipoCliente         setEmpresa()     Sets the current record's "Empresa" value
 * @method TipoCliente         setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method TipoCliente         setCliente()     Sets the current record's "Cliente" collection
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_cliente');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('orden', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Cliente', array(
             'local' => 'id',
             'foreign' => 'tipo_cliente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}