<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProveedorDescuento', 'doctrine');

/**
 * BaseProveedorDescuento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $tipo
 * @property integer $status
 * @property integer $categoria_id
 * @property integer $proveedor_id
 * @property string $nombre
 * @property integer $proveedor_sucursal_id
 * @property string $observacion
 * @property string $condiciones
 * @property string $fecha_limite
 * @property timestamp $fecha_activacion
 * @property timestamp $fecha_finalizacion
 * @property integer $num_descuentos
 * @property integer $comportamiento
 * @property integer $aplicacion
 * @property float $precio
 * @property float $precio_oferta
 * @property integer $destacado
 * @property integer $click
 * @property integer $user_id
 * @property string $user_name
 * @property string $imagen_uno
 * @property string $imagen_dos
 * @property string $imagen_tres
 * @property string $imagen_cuatro
 * @property string $imagen_cinco
 * @property Empresa $Empresa
 * @property Proveedor $Proveedor
 * @property Categoria $Categoria
 * @property ProveedorSucursal $ProveedorSucursal
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $GaleriaDescuento
 * @property Doctrine_Collection $CampoDescuento
 * @property Doctrine_Collection $VueloServicio
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getEmpresaId()             Returns the current record's "empresa_id" value
 * @method integer             getTipo()                  Returns the current record's "tipo" value
 * @method integer             getStatus()                Returns the current record's "status" value
 * @method integer             getCategoriaId()           Returns the current record's "categoria_id" value
 * @method integer             getProveedorId()           Returns the current record's "proveedor_id" value
 * @method string              getNombre()                Returns the current record's "nombre" value
 * @method integer             getProveedorSucursalId()   Returns the current record's "proveedor_sucursal_id" value
 * @method string              getObservacion()           Returns the current record's "observacion" value
 * @method string              getCondiciones()           Returns the current record's "condiciones" value
 * @method string              getFechaLimite()           Returns the current record's "fecha_limite" value
 * @method timestamp           getFechaActivacion()       Returns the current record's "fecha_activacion" value
 * @method timestamp           getFechaFinalizacion()     Returns the current record's "fecha_finalizacion" value
 * @method integer             getNumDescuentos()         Returns the current record's "num_descuentos" value
 * @method integer             getComportamiento()        Returns the current record's "comportamiento" value
 * @method integer             getAplicacion()            Returns the current record's "aplicacion" value
 * @method float               getPrecio()                Returns the current record's "precio" value
 * @method float               getPrecioOferta()          Returns the current record's "precio_oferta" value
 * @method integer             getDestacado()             Returns the current record's "destacado" value
 * @method integer             getClick()                 Returns the current record's "click" value
 * @method integer             getUserId()                Returns the current record's "user_id" value
 * @method string              getUserName()              Returns the current record's "user_name" value
 * @method string              getImagenUno()             Returns the current record's "imagen_uno" value
 * @method string              getImagenDos()             Returns the current record's "imagen_dos" value
 * @method string              getImagenTres()            Returns the current record's "imagen_tres" value
 * @method string              getImagenCuatro()          Returns the current record's "imagen_cuatro" value
 * @method string              getImagenCinco()           Returns the current record's "imagen_cinco" value
 * @method Empresa             getEmpresa()               Returns the current record's "Empresa" value
 * @method Proveedor           getProveedor()             Returns the current record's "Proveedor" value
 * @method Categoria           getCategoria()             Returns the current record's "Categoria" value
 * @method ProveedorSucursal   getProveedorSucursal()     Returns the current record's "ProveedorSucursal" value
 * @method sfGuardUser         getSfGuardUser()           Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getGaleriaDescuento()      Returns the current record's "GaleriaDescuento" collection
 * @method Doctrine_Collection getCampoDescuento()        Returns the current record's "CampoDescuento" collection
 * @method Doctrine_Collection getVueloServicio()         Returns the current record's "VueloServicio" collection
 * @method ProveedorDescuento  setId()                    Sets the current record's "id" value
 * @method ProveedorDescuento  setEmpresaId()             Sets the current record's "empresa_id" value
 * @method ProveedorDescuento  setTipo()                  Sets the current record's "tipo" value
 * @method ProveedorDescuento  setStatus()                Sets the current record's "status" value
 * @method ProveedorDescuento  setCategoriaId()           Sets the current record's "categoria_id" value
 * @method ProveedorDescuento  setProveedorId()           Sets the current record's "proveedor_id" value
 * @method ProveedorDescuento  setNombre()                Sets the current record's "nombre" value
 * @method ProveedorDescuento  setProveedorSucursalId()   Sets the current record's "proveedor_sucursal_id" value
 * @method ProveedorDescuento  setObservacion()           Sets the current record's "observacion" value
 * @method ProveedorDescuento  setCondiciones()           Sets the current record's "condiciones" value
 * @method ProveedorDescuento  setFechaLimite()           Sets the current record's "fecha_limite" value
 * @method ProveedorDescuento  setFechaActivacion()       Sets the current record's "fecha_activacion" value
 * @method ProveedorDescuento  setFechaFinalizacion()     Sets the current record's "fecha_finalizacion" value
 * @method ProveedorDescuento  setNumDescuentos()         Sets the current record's "num_descuentos" value
 * @method ProveedorDescuento  setComportamiento()        Sets the current record's "comportamiento" value
 * @method ProveedorDescuento  setAplicacion()            Sets the current record's "aplicacion" value
 * @method ProveedorDescuento  setPrecio()                Sets the current record's "precio" value
 * @method ProveedorDescuento  setPrecioOferta()          Sets the current record's "precio_oferta" value
 * @method ProveedorDescuento  setDestacado()             Sets the current record's "destacado" value
 * @method ProveedorDescuento  setClick()                 Sets the current record's "click" value
 * @method ProveedorDescuento  setUserId()                Sets the current record's "user_id" value
 * @method ProveedorDescuento  setUserName()              Sets the current record's "user_name" value
 * @method ProveedorDescuento  setImagenUno()             Sets the current record's "imagen_uno" value
 * @method ProveedorDescuento  setImagenDos()             Sets the current record's "imagen_dos" value
 * @method ProveedorDescuento  setImagenTres()            Sets the current record's "imagen_tres" value
 * @method ProveedorDescuento  setImagenCuatro()          Sets the current record's "imagen_cuatro" value
 * @method ProveedorDescuento  setImagenCinco()           Sets the current record's "imagen_cinco" value
 * @method ProveedorDescuento  setEmpresa()               Sets the current record's "Empresa" value
 * @method ProveedorDescuento  setProveedor()             Sets the current record's "Proveedor" value
 * @method ProveedorDescuento  setCategoria()             Sets the current record's "Categoria" value
 * @method ProveedorDescuento  setProveedorSucursal()     Sets the current record's "ProveedorSucursal" value
 * @method ProveedorDescuento  setSfGuardUser()           Sets the current record's "sfGuardUser" value
 * @method ProveedorDescuento  setGaleriaDescuento()      Sets the current record's "GaleriaDescuento" collection
 * @method ProveedorDescuento  setCampoDescuento()        Sets the current record's "CampoDescuento" collection
 * @method ProveedorDescuento  setVueloServicio()         Sets the current record's "VueloServicio" collection
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProveedorDescuento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proveedor_descuento');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('tipo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 1,
             'length' => 1,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('categoria_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('proveedor_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('proveedor_sucursal_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('observacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('condiciones', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_limite', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('fecha_activacion', 'timestamp', null, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha_finalizacion', 'timestamp', null, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('num_descuentos', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('comportamiento', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('aplicacion', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('precio', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             'scale' => '2',
             ));
        $this->hasColumn('precio_oferta', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             'scale' => '2',
             ));
        $this->hasColumn('destacado', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('click', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('imagen_uno', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('imagen_dos', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('imagen_tres', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('imagen_cuatro', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('imagen_cinco', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Proveedor', array(
             'local' => 'proveedor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Categoria', array(
             'local' => 'categoria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('ProveedorSucursal', array(
             'local' => 'proveedor_sucursal_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('GaleriaDescuento', array(
             'local' => 'id',
             'foreign' => 'proveedor_descuento_id'));

        $this->hasMany('CampoDescuento', array(
             'local' => 'id',
             'foreign' => 'proveedor_descuento_id'));

        $this->hasMany('VueloServicio', array(
             'local' => 'id',
             'foreign' => 'proveedor_descuento_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'uniqueBy' => 
             array(
              0 => 'nombre',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}