<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GaleriaHospedaje', 'doctrine');

/**
 * BaseGaleriaHospedaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $hospedaje_id
 * @property string $imagen
 * @property string $descripcion
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property Hospedaje $Hospedaje
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer          getId()           Returns the current record's "id" value
 * @method integer          getEmpresaId()    Returns the current record's "empresa_id" value
 * @method integer          getHospedajeId()  Returns the current record's "hospedaje_id" value
 * @method string           getImagen()       Returns the current record's "imagen" value
 * @method string           getDescripcion()  Returns the current record's "descripcion" value
 * @method integer          getUserId()       Returns the current record's "user_id" value
 * @method string           getUserName()     Returns the current record's "user_name" value
 * @method Empresa          getEmpresa()      Returns the current record's "Empresa" value
 * @method Hospedaje        getHospedaje()    Returns the current record's "Hospedaje" value
 * @method sfGuardUser      getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method GaleriaHospedaje setId()           Sets the current record's "id" value
 * @method GaleriaHospedaje setEmpresaId()    Sets the current record's "empresa_id" value
 * @method GaleriaHospedaje setHospedajeId()  Sets the current record's "hospedaje_id" value
 * @method GaleriaHospedaje setImagen()       Sets the current record's "imagen" value
 * @method GaleriaHospedaje setDescripcion()  Sets the current record's "descripcion" value
 * @method GaleriaHospedaje setUserId()       Sets the current record's "user_id" value
 * @method GaleriaHospedaje setUserName()     Sets the current record's "user_name" value
 * @method GaleriaHospedaje setEmpresa()      Sets the current record's "Empresa" value
 * @method GaleriaHospedaje setHospedaje()    Sets the current record's "Hospedaje" value
 * @method GaleriaHospedaje setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGaleriaHospedaje extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('galeria_hospedaje');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('hospedaje_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('imagen', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Hospedaje', array(
             'local' => 'hospedaje_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}