<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SeguroPrecio', 'doctrine');

/**
 * BaseSeguroPrecio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $empresa_id
 * @property integer $seguro_id
 * @property float $precio
 * @property integer $user_id
 * @property string $user_name
 * @property Empresa $Empresa
 * @property Seguro $Seguro
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getEmpresaId()   Returns the current record's "empresa_id" value
 * @method integer      getSeguroId()    Returns the current record's "seguro_id" value
 * @method float        getPrecio()      Returns the current record's "precio" value
 * @method integer      getUserId()      Returns the current record's "user_id" value
 * @method string       getUserName()    Returns the current record's "user_name" value
 * @method Empresa      getEmpresa()     Returns the current record's "Empresa" value
 * @method Seguro       getSeguro()      Returns the current record's "Seguro" value
 * @method sfGuardUser  getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method SeguroPrecio setId()          Sets the current record's "id" value
 * @method SeguroPrecio setEmpresaId()   Sets the current record's "empresa_id" value
 * @method SeguroPrecio setSeguroId()    Sets the current record's "seguro_id" value
 * @method SeguroPrecio setPrecio()      Sets the current record's "precio" value
 * @method SeguroPrecio setUserId()      Sets the current record's "user_id" value
 * @method SeguroPrecio setUserName()    Sets the current record's "user_name" value
 * @method SeguroPrecio setEmpresa()     Sets the current record's "Empresa" value
 * @method SeguroPrecio setSeguro()      Sets the current record's "Seguro" value
 * @method SeguroPrecio setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeguroPrecio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seguro_precio');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 1,
             'autoincrement' => false,
             ));
        $this->hasColumn('seguro_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('precio', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             'scale' => '2',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'default' => 1,
             ));
        $this->hasColumn('user_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Seguro', array(
             'local' => 'seguro_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}