<?php

/**
 * CampoDescuentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CampoDescuentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CampoDescuentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CampoDescuento');
    }
}