<?php

/**
 * CampoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CampoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CampoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Campo');
    }
}