<?php

/**
 * CategoriaFaqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaFaqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaFaqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoriaFaq');
    }
}