<?php

/**
 * Categoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Categoria extends BaseCategoria
{
    public function __toString() {
        return $this->getNombre();
    }
        
    static public $status = array(
        0 => 'Inactivo',
        1 => 'Activo',
    );
    
    static public $tipo= array(
        1 => 'Servicio',
        2 => 'Producto'
    );

    public function postDelete($values){
        // Elimino las fotos de la carpeta
//       if($this->getImagen()){
//            unlink(sfConfig::get('sf_upload_dir').'/categoria/'.$this->getImagen());
//       }
       //$cloud = new Cloud();
       //$cloud->nuevaNube();
    }

      
    public function postSave($event) {
       
        parent::postSave($event);
        
                $categoriaList[] =  $this->getId();
                $categoriaNombre[$this->getId()] = $this->getNombre();
                
            
            
           sfContext::getInstance()->getUser()->setAttribute('categorias',$categoriaList);
           sfContext::getInstance()->getUser()->setAttribute('categoriaNombre',$categoriaNombre);
           
    
    }

   public function save (Doctrine_Connection $conn = null){

        
        if($this->isNew()){
            $this->setOrden($this->lastOrden()+1);
        }
        $retorno = parent::save($conn);
        //$cloud = new Cloud();
        //$cloud->nuevaNube();
        
        
        
        
        return $retorno;
    }

    public function lastOrden(){

        $q = Doctrine_Query::create()
            -> from('Categoria')
            -> orderBy('orden DESC')
            -> limit('1');

        if(!$q->fetchOne()){
            
            $last=0;
            
        }else {
            
            $cate = new Categoria();
            $cate = $q->fetchOne();
            $last = $cate->getOrden();
            
        }
        return  $last;

    }

    public function  upOrden(){
        $ordenAct = $this->getOrden();
        $ordenNew = $ordenAct - 1;
        $this->orden($ordenAct, $ordenNew);


    }

    public function  downOrden(){
        $ordenAct = $this->getOrden();
        $ordenNew = $ordenAct + 1;
        $this->orden($ordenAct, $ordenNew);


    }

    public function orden($ordenAct, $ordenNew){
        $q = Doctrine_Query::create()
            -> from('Categoria')
            -> where('orden = ?', $ordenNew);

        if($q->fetchOne()){
            $cate = new Categoria();
            $cate = $q->fetchOne();
            $cate->setOrden($ordenAct);
            $cate->save();
        }
        $this->setOrden($ordenNew);
        $this->save();

    }

    public function getCategoria(){
        $q = Doctrine_Query::create()
            -> from('Categoria c')
            ->where('c.status = ?', '1')
//            ->addWhere('c.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'))
            ->orderBy('orden ASC');
       return $q->execute();
    }
    
    
    public function getCategorias(){
        $q = Doctrine_Query::create()
            -> from('Categoria c');
//            ->where('c.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'));
            $q->orderBy('orden ASC');
       return $q->execute();
    }
    
    public function getCategoriasProductos(){
        $q = Doctrine_Query::create()
            -> from('Categoria c')
//            ->where('c.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'))
            //->where('c.padre is not null')
            //->addWhere('c.tipo_id = 1')
            ->orderBy('orden ASC');
       return $q;
    }
    
    public function getCategoriaSelect(){
        $q = Doctrine_Query::create()
            -> from('Categoria c')
            ->where('c.padre is null')
            ->addWhere('c.status >0')
            ->addWhere('c.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'))
            ->orderBy('orden ASC');
       return $q;
    }
    
    public function getCategoriaSelectFront(){
        $q = Doctrine_Query::create()
            -> from('Categoria c')
            ->orderBy('orden ASC');
       return $q;
    }
    
    public function getCategoriaPorId($id){
        $q = Doctrine_Query::create()
            -> from('Categoria c')
            ->where('c.id = ?', $id)
//            ->addWhere('c.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'))
            ->orderBy('orden ASC');
       return $q->fetchOne() ;
    }

    
    public function getProductoActive(){
        $q = Doctrine_Query::create()
            -> from('Producto p')
            ->where('p.categoria_id= ?', $this->getId())
//            ->addWhere('p.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'))
            ->orderBy('orden ASC');
       return $q;
    }
    
    public function getCategoriaTipo($tipo){
        $q = Doctrine_Query::create()
            -> from('Categoria c')
            ->where('c.status = ?', '1')
            ->addWhere('tipo_id = ?', $tipo) 
//            ->addWhere('c.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'))
           ->orderBy('orden ASC');
       return $q->execute();
    }
    
    public function getCategoriaPadre($padre = NULL){
        $q = Doctrine_Query::create()
            -> from('Categoria c')
            ->where('c.status = ?', '1');
//            ->addWhere('c.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'));
           
        if($padre){
            $q->addWhere('padre = ?', $padre);
        }else {
            $q->addWhere('padre IS NULL ');
        }
            
            $q->orderBy('orden ASC');
        return $q;
    }
    
     public function getCatePadre(){
        $q = Doctrine_Query::create()
            -> from('Categoria c')
            ->where('c.status = ?', '1');
            $q->addWhere('padre is null');
//               ->addWhere('c.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'));
            $q->orderBy('orden ASC');
      
        return $q->execute();
    
     }
    
        public function getCategoriaSlug($slug){
        $q = Doctrine_Query::create()
            -> from('Categoria c')
            ->where('c.slug = ?', $slug);
//            ->addWhere('c.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'));
       return $q->fetchOne();
    }
    
    
     public function getProductoActiveEshop(){
        $q = Doctrine_Query::create()
            -> from('Producto p')
            ->leftJoin('p.CategoriaHasProducto c')   
            //-> leftJoin('p.StatusProducto s')            
            ->where('c.categoria_id= ?', $this->getId())
//            ->addWhere('p.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'))
            //->andWhere('s.id = 1')
            ->orderBy('orden ASC');
       return $q;
    }
}
