<?php

/**
 * CiudadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CiudadFinalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CiudadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CiudadFinal');
    }
    
     public function getFinalNombre(){
        $q = Doctrine_Query::create()
                ->from('CiudadFinal e');
        return $q->execute();
    }
}