<?php

/**
 * DetalleFaq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DetalleFaq extends BaseDetalleFaq
{
    
    public function __toString() {
        return $this->getDescripcion();
    }
    
    
    public function getDetalleFaqs(){
        $q = Doctrine_Query::create()
            -> from('DetalleFaq df');
            $q->orderBy('df.pregunta ASC');
       return $q->execute();
    }
    
    
    
}
