<?php

/**
 * EmpresaSeccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpresaSeccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpresaSeccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpresaSeccion');
    }
}