<?php

/**
 * ExcursionHasInclusionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcursionHasInclusionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExcursionHasInclusionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExcursionHasInclusion');
    }
}