<?php

/**
 * ExcursionHasPoliticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcursionHasPoliticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExcursionHasPoliticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExcursionHasPolitica');
    }
}