<?php

/**
 * ExcursionPrecioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcursionPrecioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExcursionPrecioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExcursionPrecio');
    }
}