<?php

/**
 * ExcursionPoliticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcursionPoliticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExcursionPoliticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExcursionPolitica');
    }
}