<?php

/**
 * ExcursionHasAdicionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcursionHasAdicionalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExcursionHasAdicionalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExcursionHasAdicional');
    }
}