<?php

/**
 * ExcursionInclusionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcursionInclusionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExcursionInclusionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExcursionInclusion');
    }
}