<?php

/**
 * ExcursionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExcursionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExcursionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Excursion');
    }
}