<?php

/**
 * GaleriaUbicacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaleriaUbicacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GaleriaUbicacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GaleriaUbicacion');
    }
}