<?php

/**
 * GaleriaDescuentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaleriaDescuentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GaleriaDescuentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GaleriaDescuento');
    }
}