<?php

/**
 * GloboTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GloboTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GloboTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Globo');
    }
}