<?php

/**
 * HospedajePagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HospedajePagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HospedajePagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HospedajePago');
    }
}