<?php

/**
 * HospedajeSucursalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HospedajeSucursalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HospedajeSucursalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HospedajeSucursal');
    }
}