<?php

/**
 * MantenimientoTanqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MantenimientoTanqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MantenimientoTanqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MantenimientoTanque');
    }
}