<?php

/**
 * MantenimientoGloboTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MantenimientoGloboTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MantenimientoGloboTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MantenimientoGlobo');
    }
}