<?php

/**
 * Pago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cronos-doctrine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Pago extends BasePago
{
    public function __toString() {
        return $this->getNombre();
    }

    static public $status = array(
        0 => 'Inactivo',
        1 => 'Activo'

    );


     public function getPago(){
        $q = Doctrine_Query::create()
            ->from('Pago p')
            ->where('p.status = ?', '1')
            ->orderBy('p.orden ASC');
       return $q->execute();
    }
    
    
   public function save (Doctrine_Connection $conn = null){


        if($this->isNew()){
            $this->setOrden($this->lastOrden()+1);
        }

        return parent::save($conn);
    }

    public function lastOrden(){

        $q = Doctrine_Query::create()
            -> from('Pago')
            -> orderBy('orden DESC')
            -> limit('1');

        if(!$q->fetchOne()){
            $last=0;
        }else {
            $pago = new Pago();
            $pago = $q->fetchOne();
            $last = $pago->getOrden();
        }
        return  $last;

    }

    public function  upOrden(){
        $ordenAct = $this->getOrden();
        $ordenNew = $ordenAct - 1;
        $this->orden($ordenAct, $ordenNew);


    }

    public function  downOrden(){
        $ordenAct = $this->getOrden();
        $ordenNew = $ordenAct + 1;
        $this->orden($ordenAct, $ordenNew);


    }

    public function orden($ordenAct, $ordenNew){
        $q = Doctrine_Query::create()
            -> from('Pago')
            -> where('orden = ?', $ordenNew);

        if($q->fetchOne()){
            $pago = new Pago();
            $pago = $q->fetchOne();
            $pago->setOrden($ordenAct);
            $pago->save();
        }
        $this->setOrden($ordenNew);
        $this->save();

    }

    public function postDelete($values){
        // Elimino las fotos de la carpeta
       if($this->getImagen()){
            unlink(sfConfig::get('sf_upload_dir').'/pago/'.$this->getImagen());
       }
    }
    
   public function postSave($values){
        
   
           $pago = new Pago();
           $pagos = $pago->getPagosSelect()->execute();
           foreach ($pagos as $pago){
               sfContext::getInstance()->getUser()->setAttribute('pago'.$pago->getId(),$pago->getNombre());
               sfContext::getInstance()->getUser()->setAttribute('pago_imagen'.$pago->getId(),$pago->getImagen());
           }
        
        
    }    
    
    
   
    
          
    public function getPagos(){
        $q = Doctrine_Query::create()
            -> from('Pago c')
            ->orderBy('c.nombre ASC');
       return $q->execute();
    }
    
     public function getPagosSelect(){
        $q = Doctrine_Query::create()
            -> from('Pago c')
            ->where('c.status = 1')
            ->orderBy('c.nombre ASC');
       return $q;
    }

}
