<?php

/**
 * ProveedorSucursal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProveedorSucursal extends BaseProveedorSucursal
{
    
    public function __toString() {
        return $this->getNombre();
    }
    
     public function getSucursalesCtte($id){
        $q = Doctrine_Query::create()
                ->from('ProveedorSucursal c')
                ->where('c.proveedor_id=?', $id)
                ->orderBy('c.nombre asc');
        return $q;
    }
    
}
