<?php

/**
 * ProveedorPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProveedorPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProveedorPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProveedorPago');
    }
}