<?php

/**
 * ProveedorVueloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProveedorVueloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProveedorVueloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProveedorVuelo');
    }
}