<?php

/**
 * ProveedorDescuentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProveedorDescuentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProveedorDescuentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProveedorDescuento');
    }
}