<?php

/**
 * ProveedorRedeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProveedorRedeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProveedorRedeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProveedorRede');
    }
}