<?php

/**
 * RangoEdad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RangoEdad extends BaseRangoEdad
{
    
      public function __toString() {
        return $this->getNombre().' ( '.$this->getRangoDesde().' - '.$this->getRangoHasta().' )';
    }

    static public $status = array(
        0 => 'Inactivo',
        1 => 'Activo'

    );


     public function getRangoEdades(){
        $q = Doctrine_Query::create()
            ->from('RangoEdad p');
       return $q->execute();
    }
    
    
     public function postSave($values){

        $rango_edades = new RangoEdad();
           $rango_edades = $rango_edades->getRangoEdades();
           foreach ($rango_edades as $rango_edad){
               sfContext::getInstance()->getUser()->setAttribute('rango_edad'.$rango_edad->getId(),$rango_edad->getNombre().' ( '.$rango_edad->getRangoDesde().' - '.$rango_edad->getRangoHasta().' )');
           }
    }
    
    
}
