<?php

/**
 * RangoEdadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RangoEdadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RangoEdadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RangoEdad');
    }
}