<?php

/**
 * RedeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RedeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RedeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rede');
    }
}