<?php

/**
 * SeguroPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeguroPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeguroPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeguroPlan');
    }
}