<?php

/**
 * SeguroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeguroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeguroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Seguro');
    }
}