<?php

/**
 * Tanque
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tanque extends BaseTanque
{
    
     
     public function __toString() {
        return $this->getNumeroSerie();
    }
    
    
          
    public function getTanquees(){
        $q = Doctrine_Query::create()
            -> from('Tanque c')
            ->orderBy('c.id ASC');
       return $q->execute();
    }
    
    
}
