<?php

/**
 * TipoTarifaPrecioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoTarifaPrecioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoTarifaPrecioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoTarifaPrecio');
    }
}