<?php

/**
 * TipoMotivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TipoMotivo extends BaseTipoMotivo
{
    
    
      public function __toString() {
        return $this->getNombre();
    }
    
    
     
    public function getTipoMotivos(){
        
         $q = Doctrine_Query::create()
            -> from('TipoMotivo p')
            ->where('p.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'));
            
       return $q;
        
    }
    
}
