<?php

/**
 * TipoHabitacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoHabitacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoHabitacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoHabitacion');
    }
}