<?php

/**
 * TipoRestriciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TipoRestriciones extends BaseTipoRestriciones
{
    
     public function __toString() {
        return $this->getNombre();
    }
    
    
     
    public function getTipoRestriciones(){
        
         $q = Doctrine_Query::create()
            -> from('TipoRestriciones p')
            ->where('p.empresa_id=?', sfContext::getInstance()->getUser()->getAttribute('agente_user_empresa_id'));
            
       return $q;
        
    }
    
      public function postSave($values){

         
            $tipo_restriciones = new TipoRestriciones();
           $tipo_restriciones = $tipo_restriciones->getTipoRestriciones()->execute();
           foreach ($tipo_restriciones as $tipo_restricion){
               sfContext::getInstance()->getUser()->setAttribute('restriciones'.$tipo_restricion->getId(),$tipo_restricion->getNombre());
           }
          
          
    }
    
    
}
