<?php

/**
 * TipoTarifaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoTarifaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoTarifaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoTarifa');
    }
}