<?php

/**
 * TipoClienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoCliente');
    }
}