<?php

/**
 * TipoRecomendacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoRecomendacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoRecomendacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoRecomendaciones');
    }
}