<?php

/**
 * TipoCanastillaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoCanastillaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoCanastillaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoCanastilla');
    }
}