<?php

/**
 * TipoLonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoLonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoLonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoLona');
    }
}