<?php

/**
 * TipoRestricionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoRestricionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoRestricionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoRestriciones');
    }
}