<?php

/**
 * TipoPersonalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoPersonalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoPersonalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoPersonal');
    }
}