<?php

/**
 * Ubicacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ubicacion extends BaseUbicacion
{
    
       public function __toString() {
        return $this->getNombre();
    }

    
    public function getUbicaciones(){
        $q = Doctrine_Query::create()
            -> from('Ubicacion p')
            ->orderBy('p.nombre ASC');
       return $q->execute();
    }
    
    public function getUbicacionesSelect(){
        $q = Doctrine_Query::create()
            -> from('Ubicacion p')
            ->orderBy('p.nombre ASC');
       return $q;
    }
    
    
}
