<?php

/**
 * VehiculoPrecioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiculoPrecioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiculoPrecioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehiculoPrecio');
    }
}