<?php

/**
 * VehiculoTipoTransmisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiculoTipoTransmisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiculoTipoTransmisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehiculoTipoTransmision');
    }
}