<?php

/**
 * VehiculoMarcaModeloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiculoMarcaModeloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiculoMarcaModeloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehiculoMarcaModelo');
    }
    
    public function getNombre() {
        $q = Doctrine_Query::create()
                ->from('VehiculoMarcaModelo e')
                ->orderBy('e.nombre asc');
        return $q->execute();
    }

}