<?php

/**
 * VehiculoHasSeguroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiculoHasSeguroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiculoHasSeguroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehiculoHasSeguro');
    }
}