<?php

/**
 * VehiculoSeguro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VehiculoSeguro extends BaseVehiculoSeguro
{
    
    public function __toString() {
        return $this->getNombre();
    }

    public function getVehiculoSeguros() {
        $q = Doctrine_Query::create()
                ->from('VehiculoSeguro c');
        $q->orderBy('c.nombre ASC');
        return $q->execute();
    }
    
    static public $status = array(
        0 => 'Inactivo',
        1 => 'Activo',
    );
    
         public function postSave($values){
   
         $vehiculo_seguros = new VehiculoSeguro();
           $vehiculo_seguros = $vehiculo_seguros->getVehiculoSeguros();
           foreach ($vehiculo_seguros as $vehiculo_seguro){
               sfContext::getInstance()->getUser()->setAttribute('vehiculos_seguros'.$vehiculo_seguro->getId(),$vehiculo_seguro->getNombre());
           }
         
         
         
    }  
}
