<?php

/**
 * VehiculoTipoReproductorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiculoTipoReproductorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiculoTipoReproductorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VehiculoTipoReproductor');
    }
}