<?php

/**
 * VueloRestricionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VueloRestricionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VueloRestricionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VueloRestriciones');
    }
}