<?php

/**
 * VueloClienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VueloClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VueloClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VueloCliente');
    }
}