<?php

/**
 * VueloServicioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VueloServicioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VueloServicioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VueloServicio');
    }
}