<?php

/**
 * VueloRecomendacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VueloRecomendacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VueloRecomendacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VueloRecomendaciones');
    }
}