<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $identificacion
 * @property date $fecha_nacimiento
 * @property string $direcion
 * @property string $telefono_principal
 * @property integer $sexo
 * @property integer $tipo_personal_id
 * @property string $edo_civil
 * @property string $nacionalidad
 * @property integer $empresa_id
 * @property string $ocupacion
 * @property string $titulo
 * @property string $grado_instruccion
 * @property string $email_address
 * @property string $username
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property timestamp $last_login
 * @property string $alerta
 * @property string $observacion
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Permissions
 * @property Empresa $Empresa
 * @property TipoPersonal $TipoPersonal
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property sfGuardRememberKey $RememberKeys
 * @property sfGuardForgotPassword $ForgotPassword
 * @property Doctrine_Collection $Pais
 * @property Doctrine_Collection $RangoEdad
 * @property Doctrine_Collection $TipoTarifa
 * @property Doctrine_Collection $TipoTarifaPrecio
 * @property Doctrine_Collection $TipoCliente
 * @property Doctrine_Collection $Proveedor
 * @property Doctrine_Collection $ProveedorSucursal
 * @property Doctrine_Collection $GaleriaProveedor
 * @property Doctrine_Collection $GaleriaDescuento
 * @property Doctrine_Collection $ProveedorDescuento
 * @property Doctrine_Collection $ProveedorRede
 * @property Doctrine_Collection $ProveedorPago
 * @property Doctrine_Collection $Categoria
 * @property Doctrine_Collection $Ciudad
 * @property Doctrine_Collection $Pago
 * @property Doctrine_Collection $Provincia
 * @property Doctrine_Collection $Ubicacion
 * @property Doctrine_Collection $GaleriaUbicacion
 * @property Doctrine_Collection $Rede
 * @property Doctrine_Collection $Campo
 * @property Doctrine_Collection $CampoDescuento
 * @property Doctrine_Collection $CategoriaFaq
 * @property Doctrine_Collection $DetalleFaq
 * @property Doctrine_Collection $EmpresaSeccion
 * @property Doctrine_Collection $TipoVuelo
 * @property Doctrine_Collection $TipoMotivo
 * @property Doctrine_Collection $TipoLona
 * @property Doctrine_Collection $TipoRestriciones
 * @property Doctrine_Collection $TipoRecomendaciones
 * @property Doctrine_Collection $Globo
 * @property Doctrine_Collection $MantenimientoGlobo
 * @property Doctrine_Collection $ProveedorVuelo
 * @property Doctrine_Collection $VueloRestriciones
 * @property Doctrine_Collection $VueloRecomendaciones
 * @property Doctrine_Collection $VueloServicio
 * @property Doctrine_Collection $VueloHospedaje
 * @property Doctrine_Collection $Cliente
 * @property Doctrine_Collection $VueloCliente
 * @property Doctrine_Collection $Marca
 * @property Doctrine_Collection $Quemador
 * @property Doctrine_Collection $MantenimientoQuemador
 * @property Doctrine_Collection $TipoCanastilla
 * @property Doctrine_Collection $Canastilla
 * @property Doctrine_Collection $MantenimientoCanastilla
 * @property Doctrine_Collection $Tanque
 * @property Doctrine_Collection $MantenimientoTanque
 * @property Doctrine_Collection $TipoHabitacion
 * @property Doctrine_Collection $TipoCama
 * @property Doctrine_Collection $Hospedaje
 * @property Doctrine_Collection $HospedajeHabitacion
 * @property Doctrine_Collection $GaleriaHospedaje
 * @property Doctrine_Collection $HospedajeRede
 * @property Doctrine_Collection $HospedajePago
 * @property Doctrine_Collection $Vehiculo
 * @property Doctrine_Collection $VehiculoHasPolitica
 * @property Doctrine_Collection $VehiculoHasSeguro
 * @property Doctrine_Collection $VehiculoHasAdicional
 * @property Doctrine_Collection $VehiculoCategoria
 * @property Doctrine_Collection $VehiculoTipoReproductor
 * @property Doctrine_Collection $VehiculoMarca
 * @property Doctrine_Collection $VehiculoMarcaModelo
 * @property Doctrine_Collection $VehiculoTipo
 * @property Doctrine_Collection $VehiculoTipoTransmision
 * @property Doctrine_Collection $VehiculoPrecio
 * @property Doctrine_Collection $VehiculoAdicional
 * @property Doctrine_Collection $VehiculoPolitica
 * @property Doctrine_Collection $VehiculoSeguro
 * @property Doctrine_Collection $Seguro
 * @property Doctrine_Collection $SeguroTipo
 * @property Doctrine_Collection $SeguroPlan
 * @property Doctrine_Collection $SeguroBeneficio
 * @property Doctrine_Collection $SeguroHasBeneficio
 * @property Doctrine_Collection $SeguroPrecio
 * @property Doctrine_Collection $Excursion
 * @property Doctrine_Collection $ExcursionAdicional
 * @property Doctrine_Collection $ExcursionPolitica
 * @property Doctrine_Collection $ExcursionLugarInteres
 * @property Doctrine_Collection $ExcursionRequisito
 * @property Doctrine_Collection $ExcursionIncluible
 * @property Doctrine_Collection $ExcursionHasAdicional
 * @property Doctrine_Collection $ExcursionHasPolitica
 * @property Doctrine_Collection $ExcursionHasLugarInteres
 * @property Doctrine_Collection $ExcursionHasInclusion
 * @property Doctrine_Collection $ExcursionHasRequisito
 * @property Doctrine_Collection $ExcursionPrecio
 * 
 * @method string                getFirstName()                Returns the current record's "first_name" value
 * @method string                getLastName()                 Returns the current record's "last_name" value
 * @method string                getIdentificacion()           Returns the current record's "identificacion" value
 * @method date                  getFechaNacimiento()          Returns the current record's "fecha_nacimiento" value
 * @method string                getDirecion()                 Returns the current record's "direcion" value
 * @method string                getTelefonoPrincipal()        Returns the current record's "telefono_principal" value
 * @method integer               getSexo()                     Returns the current record's "sexo" value
 * @method integer               getTipoPersonalId()           Returns the current record's "tipo_personal_id" value
 * @method string                getEdoCivil()                 Returns the current record's "edo_civil" value
 * @method string                getNacionalidad()             Returns the current record's "nacionalidad" value
 * @method integer               getEmpresaId()                Returns the current record's "empresa_id" value
 * @method string                getOcupacion()                Returns the current record's "ocupacion" value
 * @method string                getTitulo()                   Returns the current record's "titulo" value
 * @method string                getGradoInstruccion()         Returns the current record's "grado_instruccion" value
 * @method string                getEmailAddress()             Returns the current record's "email_address" value
 * @method string                getUsername()                 Returns the current record's "username" value
 * @method string                getAlgorithm()                Returns the current record's "algorithm" value
 * @method string                getSalt()                     Returns the current record's "salt" value
 * @method string                getPassword()                 Returns the current record's "password" value
 * @method boolean               getIsActive()                 Returns the current record's "is_active" value
 * @method boolean               getIsSuperAdmin()             Returns the current record's "is_super_admin" value
 * @method timestamp             getLastLogin()                Returns the current record's "last_login" value
 * @method string                getAlerta()                   Returns the current record's "alerta" value
 * @method string                getObservacion()              Returns the current record's "observacion" value
 * @method Doctrine_Collection   getGroups()                   Returns the current record's "Groups" collection
 * @method Doctrine_Collection   getPermissions()              Returns the current record's "Permissions" collection
 * @method Empresa               getEmpresa()                  Returns the current record's "Empresa" value
 * @method TipoPersonal          getTipoPersonal()             Returns the current record's "TipoPersonal" value
 * @method Doctrine_Collection   getSfGuardUserPermission()    Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection   getSfGuardUserGroup()         Returns the current record's "sfGuardUserGroup" collection
 * @method sfGuardRememberKey    getRememberKeys()             Returns the current record's "RememberKeys" value
 * @method sfGuardForgotPassword getForgotPassword()           Returns the current record's "ForgotPassword" value
 * @method Doctrine_Collection   getPais()                     Returns the current record's "Pais" collection
 * @method Doctrine_Collection   getRangoEdad()                Returns the current record's "RangoEdad" collection
 * @method Doctrine_Collection   getTipoTarifa()               Returns the current record's "TipoTarifa" collection
 * @method Doctrine_Collection   getTipoTarifaPrecio()         Returns the current record's "TipoTarifaPrecio" collection
 * @method Doctrine_Collection   getTipoCliente()              Returns the current record's "TipoCliente" collection
 * @method Doctrine_Collection   getProveedor()                Returns the current record's "Proveedor" collection
 * @method Doctrine_Collection   getProveedorSucursal()        Returns the current record's "ProveedorSucursal" collection
 * @method Doctrine_Collection   getGaleriaProveedor()         Returns the current record's "GaleriaProveedor" collection
 * @method Doctrine_Collection   getGaleriaDescuento()         Returns the current record's "GaleriaDescuento" collection
 * @method Doctrine_Collection   getProveedorDescuento()       Returns the current record's "ProveedorDescuento" collection
 * @method Doctrine_Collection   getProveedorRede()            Returns the current record's "ProveedorRede" collection
 * @method Doctrine_Collection   getProveedorPago()            Returns the current record's "ProveedorPago" collection
 * @method Doctrine_Collection   getCategoria()                Returns the current record's "Categoria" collection
 * @method Doctrine_Collection   getCiudad()                   Returns the current record's "Ciudad" collection
 * @method Doctrine_Collection   getPago()                     Returns the current record's "Pago" collection
 * @method Doctrine_Collection   getProvincia()                Returns the current record's "Provincia" collection
 * @method Doctrine_Collection   getUbicacion()                Returns the current record's "Ubicacion" collection
 * @method Doctrine_Collection   getGaleriaUbicacion()         Returns the current record's "GaleriaUbicacion" collection
 * @method Doctrine_Collection   getRede()                     Returns the current record's "Rede" collection
 * @method Doctrine_Collection   getCampo()                    Returns the current record's "Campo" collection
 * @method Doctrine_Collection   getCampoDescuento()           Returns the current record's "CampoDescuento" collection
 * @method Doctrine_Collection   getCategoriaFaq()             Returns the current record's "CategoriaFaq" collection
 * @method Doctrine_Collection   getDetalleFaq()               Returns the current record's "DetalleFaq" collection
 * @method Doctrine_Collection   getEmpresaSeccion()           Returns the current record's "EmpresaSeccion" collection
 * @method Doctrine_Collection   getTipoVuelo()                Returns the current record's "TipoVuelo" collection
 * @method Doctrine_Collection   getTipoMotivo()               Returns the current record's "TipoMotivo" collection
 * @method Doctrine_Collection   getTipoLona()                 Returns the current record's "TipoLona" collection
 * @method Doctrine_Collection   getTipoRestriciones()         Returns the current record's "TipoRestriciones" collection
 * @method Doctrine_Collection   getTipoRecomendaciones()      Returns the current record's "TipoRecomendaciones" collection
 * @method Doctrine_Collection   getGlobo()                    Returns the current record's "Globo" collection
 * @method Doctrine_Collection   getMantenimientoGlobo()       Returns the current record's "MantenimientoGlobo" collection
 * @method Doctrine_Collection   getProveedorVuelo()           Returns the current record's "ProveedorVuelo" collection
 * @method Doctrine_Collection   getVueloRestriciones()        Returns the current record's "VueloRestriciones" collection
 * @method Doctrine_Collection   getVueloRecomendaciones()     Returns the current record's "VueloRecomendaciones" collection
 * @method Doctrine_Collection   getVueloServicio()            Returns the current record's "VueloServicio" collection
 * @method Doctrine_Collection   getVueloHospedaje()           Returns the current record's "VueloHospedaje" collection
 * @method Doctrine_Collection   getCliente()                  Returns the current record's "Cliente" collection
 * @method Doctrine_Collection   getVueloCliente()             Returns the current record's "VueloCliente" collection
 * @method Doctrine_Collection   getMarca()                    Returns the current record's "Marca" collection
 * @method Doctrine_Collection   getQuemador()                 Returns the current record's "Quemador" collection
 * @method Doctrine_Collection   getMantenimientoQuemador()    Returns the current record's "MantenimientoQuemador" collection
 * @method Doctrine_Collection   getTipoCanastilla()           Returns the current record's "TipoCanastilla" collection
 * @method Doctrine_Collection   getCanastilla()               Returns the current record's "Canastilla" collection
 * @method Doctrine_Collection   getMantenimientoCanastilla()  Returns the current record's "MantenimientoCanastilla" collection
 * @method Doctrine_Collection   getTanque()                   Returns the current record's "Tanque" collection
 * @method Doctrine_Collection   getMantenimientoTanque()      Returns the current record's "MantenimientoTanque" collection
 * @method Doctrine_Collection   getTipoHabitacion()           Returns the current record's "TipoHabitacion" collection
 * @method Doctrine_Collection   getTipoCama()                 Returns the current record's "TipoCama" collection
 * @method Doctrine_Collection   getHospedaje()                Returns the current record's "Hospedaje" collection
 * @method Doctrine_Collection   getHospedajeHabitacion()      Returns the current record's "HospedajeHabitacion" collection
 * @method Doctrine_Collection   getGaleriaHospedaje()         Returns the current record's "GaleriaHospedaje" collection
 * @method Doctrine_Collection   getHospedajeRede()            Returns the current record's "HospedajeRede" collection
 * @method Doctrine_Collection   getHospedajePago()            Returns the current record's "HospedajePago" collection
 * @method Doctrine_Collection   getVehiculo()                 Returns the current record's "Vehiculo" collection
 * @method Doctrine_Collection   getVehiculoHasPolitica()      Returns the current record's "VehiculoHasPolitica" collection
 * @method Doctrine_Collection   getVehiculoHasSeguro()        Returns the current record's "VehiculoHasSeguro" collection
 * @method Doctrine_Collection   getVehiculoHasAdicional()     Returns the current record's "VehiculoHasAdicional" collection
 * @method Doctrine_Collection   getVehiculoCategoria()        Returns the current record's "VehiculoCategoria" collection
 * @method Doctrine_Collection   getVehiculoTipoReproductor()  Returns the current record's "VehiculoTipoReproductor" collection
 * @method Doctrine_Collection   getVehiculoMarca()            Returns the current record's "VehiculoMarca" collection
 * @method Doctrine_Collection   getVehiculoMarcaModelo()      Returns the current record's "VehiculoMarcaModelo" collection
 * @method Doctrine_Collection   getVehiculoTipo()             Returns the current record's "VehiculoTipo" collection
 * @method Doctrine_Collection   getVehiculoTipoTransmision()  Returns the current record's "VehiculoTipoTransmision" collection
 * @method Doctrine_Collection   getVehiculoPrecio()           Returns the current record's "VehiculoPrecio" collection
 * @method Doctrine_Collection   getVehiculoAdicional()        Returns the current record's "VehiculoAdicional" collection
 * @method Doctrine_Collection   getVehiculoPolitica()         Returns the current record's "VehiculoPolitica" collection
 * @method Doctrine_Collection   getVehiculoSeguro()           Returns the current record's "VehiculoSeguro" collection
 * @method Doctrine_Collection   getSeguro()                   Returns the current record's "Seguro" collection
 * @method Doctrine_Collection   getSeguroTipo()               Returns the current record's "SeguroTipo" collection
 * @method Doctrine_Collection   getSeguroPlan()               Returns the current record's "SeguroPlan" collection
 * @method Doctrine_Collection   getSeguroBeneficio()          Returns the current record's "SeguroBeneficio" collection
 * @method Doctrine_Collection   getSeguroHasBeneficio()       Returns the current record's "SeguroHasBeneficio" collection
 * @method Doctrine_Collection   getSeguroPrecio()             Returns the current record's "SeguroPrecio" collection
 * @method Doctrine_Collection   getExcursion()                Returns the current record's "Excursion" collection
 * @method Doctrine_Collection   getExcursionAdicional()       Returns the current record's "ExcursionAdicional" collection
 * @method Doctrine_Collection   getExcursionPolitica()        Returns the current record's "ExcursionPolitica" collection
 * @method Doctrine_Collection   getExcursionLugarInteres()    Returns the current record's "ExcursionLugarInteres" collection
 * @method Doctrine_Collection   getExcursionRequisito()       Returns the current record's "ExcursionRequisito" collection
 * @method Doctrine_Collection   getExcursionIncluible()       Returns the current record's "ExcursionIncluible" collection
 * @method Doctrine_Collection   getExcursionHasAdicional()    Returns the current record's "ExcursionHasAdicional" collection
 * @method Doctrine_Collection   getExcursionHasPolitica()     Returns the current record's "ExcursionHasPolitica" collection
 * @method Doctrine_Collection   getExcursionHasLugarInteres() Returns the current record's "ExcursionHasLugarInteres" collection
 * @method Doctrine_Collection   getExcursionHasInclusion()    Returns the current record's "ExcursionHasInclusion" collection
 * @method Doctrine_Collection   getExcursionHasRequisito()    Returns the current record's "ExcursionHasRequisito" collection
 * @method Doctrine_Collection   getExcursionPrecio()          Returns the current record's "ExcursionPrecio" collection
 * @method sfGuardUser           setFirstName()                Sets the current record's "first_name" value
 * @method sfGuardUser           setLastName()                 Sets the current record's "last_name" value
 * @method sfGuardUser           setIdentificacion()           Sets the current record's "identificacion" value
 * @method sfGuardUser           setFechaNacimiento()          Sets the current record's "fecha_nacimiento" value
 * @method sfGuardUser           setDirecion()                 Sets the current record's "direcion" value
 * @method sfGuardUser           setTelefonoPrincipal()        Sets the current record's "telefono_principal" value
 * @method sfGuardUser           setSexo()                     Sets the current record's "sexo" value
 * @method sfGuardUser           setTipoPersonalId()           Sets the current record's "tipo_personal_id" value
 * @method sfGuardUser           setEdoCivil()                 Sets the current record's "edo_civil" value
 * @method sfGuardUser           setNacionalidad()             Sets the current record's "nacionalidad" value
 * @method sfGuardUser           setEmpresaId()                Sets the current record's "empresa_id" value
 * @method sfGuardUser           setOcupacion()                Sets the current record's "ocupacion" value
 * @method sfGuardUser           setTitulo()                   Sets the current record's "titulo" value
 * @method sfGuardUser           setGradoInstruccion()         Sets the current record's "grado_instruccion" value
 * @method sfGuardUser           setEmailAddress()             Sets the current record's "email_address" value
 * @method sfGuardUser           setUsername()                 Sets the current record's "username" value
 * @method sfGuardUser           setAlgorithm()                Sets the current record's "algorithm" value
 * @method sfGuardUser           setSalt()                     Sets the current record's "salt" value
 * @method sfGuardUser           setPassword()                 Sets the current record's "password" value
 * @method sfGuardUser           setIsActive()                 Sets the current record's "is_active" value
 * @method sfGuardUser           setIsSuperAdmin()             Sets the current record's "is_super_admin" value
 * @method sfGuardUser           setLastLogin()                Sets the current record's "last_login" value
 * @method sfGuardUser           setAlerta()                   Sets the current record's "alerta" value
 * @method sfGuardUser           setObservacion()              Sets the current record's "observacion" value
 * @method sfGuardUser           setGroups()                   Sets the current record's "Groups" collection
 * @method sfGuardUser           setPermissions()              Sets the current record's "Permissions" collection
 * @method sfGuardUser           setEmpresa()                  Sets the current record's "Empresa" value
 * @method sfGuardUser           setTipoPersonal()             Sets the current record's "TipoPersonal" value
 * @method sfGuardUser           setSfGuardUserPermission()    Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardUser           setSfGuardUserGroup()         Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardUser           setRememberKeys()             Sets the current record's "RememberKeys" value
 * @method sfGuardUser           setForgotPassword()           Sets the current record's "ForgotPassword" value
 * @method sfGuardUser           setPais()                     Sets the current record's "Pais" collection
 * @method sfGuardUser           setRangoEdad()                Sets the current record's "RangoEdad" collection
 * @method sfGuardUser           setTipoTarifa()               Sets the current record's "TipoTarifa" collection
 * @method sfGuardUser           setTipoTarifaPrecio()         Sets the current record's "TipoTarifaPrecio" collection
 * @method sfGuardUser           setTipoCliente()              Sets the current record's "TipoCliente" collection
 * @method sfGuardUser           setProveedor()                Sets the current record's "Proveedor" collection
 * @method sfGuardUser           setProveedorSucursal()        Sets the current record's "ProveedorSucursal" collection
 * @method sfGuardUser           setGaleriaProveedor()         Sets the current record's "GaleriaProveedor" collection
 * @method sfGuardUser           setGaleriaDescuento()         Sets the current record's "GaleriaDescuento" collection
 * @method sfGuardUser           setProveedorDescuento()       Sets the current record's "ProveedorDescuento" collection
 * @method sfGuardUser           setProveedorRede()            Sets the current record's "ProveedorRede" collection
 * @method sfGuardUser           setProveedorPago()            Sets the current record's "ProveedorPago" collection
 * @method sfGuardUser           setCategoria()                Sets the current record's "Categoria" collection
 * @method sfGuardUser           setCiudad()                   Sets the current record's "Ciudad" collection
 * @method sfGuardUser           setPago()                     Sets the current record's "Pago" collection
 * @method sfGuardUser           setProvincia()                Sets the current record's "Provincia" collection
 * @method sfGuardUser           setUbicacion()                Sets the current record's "Ubicacion" collection
 * @method sfGuardUser           setGaleriaUbicacion()         Sets the current record's "GaleriaUbicacion" collection
 * @method sfGuardUser           setRede()                     Sets the current record's "Rede" collection
 * @method sfGuardUser           setCampo()                    Sets the current record's "Campo" collection
 * @method sfGuardUser           setCampoDescuento()           Sets the current record's "CampoDescuento" collection
 * @method sfGuardUser           setCategoriaFaq()             Sets the current record's "CategoriaFaq" collection
 * @method sfGuardUser           setDetalleFaq()               Sets the current record's "DetalleFaq" collection
 * @method sfGuardUser           setEmpresaSeccion()           Sets the current record's "EmpresaSeccion" collection
 * @method sfGuardUser           setTipoVuelo()                Sets the current record's "TipoVuelo" collection
 * @method sfGuardUser           setTipoMotivo()               Sets the current record's "TipoMotivo" collection
 * @method sfGuardUser           setTipoLona()                 Sets the current record's "TipoLona" collection
 * @method sfGuardUser           setTipoRestriciones()         Sets the current record's "TipoRestriciones" collection
 * @method sfGuardUser           setTipoRecomendaciones()      Sets the current record's "TipoRecomendaciones" collection
 * @method sfGuardUser           setGlobo()                    Sets the current record's "Globo" collection
 * @method sfGuardUser           setMantenimientoGlobo()       Sets the current record's "MantenimientoGlobo" collection
 * @method sfGuardUser           setProveedorVuelo()           Sets the current record's "ProveedorVuelo" collection
 * @method sfGuardUser           setVueloRestriciones()        Sets the current record's "VueloRestriciones" collection
 * @method sfGuardUser           setVueloRecomendaciones()     Sets the current record's "VueloRecomendaciones" collection
 * @method sfGuardUser           setVueloServicio()            Sets the current record's "VueloServicio" collection
 * @method sfGuardUser           setVueloHospedaje()           Sets the current record's "VueloHospedaje" collection
 * @method sfGuardUser           setCliente()                  Sets the current record's "Cliente" collection
 * @method sfGuardUser           setVueloCliente()             Sets the current record's "VueloCliente" collection
 * @method sfGuardUser           setMarca()                    Sets the current record's "Marca" collection
 * @method sfGuardUser           setQuemador()                 Sets the current record's "Quemador" collection
 * @method sfGuardUser           setMantenimientoQuemador()    Sets the current record's "MantenimientoQuemador" collection
 * @method sfGuardUser           setTipoCanastilla()           Sets the current record's "TipoCanastilla" collection
 * @method sfGuardUser           setCanastilla()               Sets the current record's "Canastilla" collection
 * @method sfGuardUser           setMantenimientoCanastilla()  Sets the current record's "MantenimientoCanastilla" collection
 * @method sfGuardUser           setTanque()                   Sets the current record's "Tanque" collection
 * @method sfGuardUser           setMantenimientoTanque()      Sets the current record's "MantenimientoTanque" collection
 * @method sfGuardUser           setTipoHabitacion()           Sets the current record's "TipoHabitacion" collection
 * @method sfGuardUser           setTipoCama()                 Sets the current record's "TipoCama" collection
 * @method sfGuardUser           setHospedaje()                Sets the current record's "Hospedaje" collection
 * @method sfGuardUser           setHospedajeHabitacion()      Sets the current record's "HospedajeHabitacion" collection
 * @method sfGuardUser           setGaleriaHospedaje()         Sets the current record's "GaleriaHospedaje" collection
 * @method sfGuardUser           setHospedajeRede()            Sets the current record's "HospedajeRede" collection
 * @method sfGuardUser           setHospedajePago()            Sets the current record's "HospedajePago" collection
 * @method sfGuardUser           setVehiculo()                 Sets the current record's "Vehiculo" collection
 * @method sfGuardUser           setVehiculoHasPolitica()      Sets the current record's "VehiculoHasPolitica" collection
 * @method sfGuardUser           setVehiculoHasSeguro()        Sets the current record's "VehiculoHasSeguro" collection
 * @method sfGuardUser           setVehiculoHasAdicional()     Sets the current record's "VehiculoHasAdicional" collection
 * @method sfGuardUser           setVehiculoCategoria()        Sets the current record's "VehiculoCategoria" collection
 * @method sfGuardUser           setVehiculoTipoReproductor()  Sets the current record's "VehiculoTipoReproductor" collection
 * @method sfGuardUser           setVehiculoMarca()            Sets the current record's "VehiculoMarca" collection
 * @method sfGuardUser           setVehiculoMarcaModelo()      Sets the current record's "VehiculoMarcaModelo" collection
 * @method sfGuardUser           setVehiculoTipo()             Sets the current record's "VehiculoTipo" collection
 * @method sfGuardUser           setVehiculoTipoTransmision()  Sets the current record's "VehiculoTipoTransmision" collection
 * @method sfGuardUser           setVehiculoPrecio()           Sets the current record's "VehiculoPrecio" collection
 * @method sfGuardUser           setVehiculoAdicional()        Sets the current record's "VehiculoAdicional" collection
 * @method sfGuardUser           setVehiculoPolitica()         Sets the current record's "VehiculoPolitica" collection
 * @method sfGuardUser           setVehiculoSeguro()           Sets the current record's "VehiculoSeguro" collection
 * @method sfGuardUser           setSeguro()                   Sets the current record's "Seguro" collection
 * @method sfGuardUser           setSeguroTipo()               Sets the current record's "SeguroTipo" collection
 * @method sfGuardUser           setSeguroPlan()               Sets the current record's "SeguroPlan" collection
 * @method sfGuardUser           setSeguroBeneficio()          Sets the current record's "SeguroBeneficio" collection
 * @method sfGuardUser           setSeguroHasBeneficio()       Sets the current record's "SeguroHasBeneficio" collection
 * @method sfGuardUser           setSeguroPrecio()             Sets the current record's "SeguroPrecio" collection
 * @method sfGuardUser           setExcursion()                Sets the current record's "Excursion" collection
 * @method sfGuardUser           setExcursionAdicional()       Sets the current record's "ExcursionAdicional" collection
 * @method sfGuardUser           setExcursionPolitica()        Sets the current record's "ExcursionPolitica" collection
 * @method sfGuardUser           setExcursionLugarInteres()    Sets the current record's "ExcursionLugarInteres" collection
 * @method sfGuardUser           setExcursionRequisito()       Sets the current record's "ExcursionRequisito" collection
 * @method sfGuardUser           setExcursionIncluible()       Sets the current record's "ExcursionIncluible" collection
 * @method sfGuardUser           setExcursionHasAdicional()    Sets the current record's "ExcursionHasAdicional" collection
 * @method sfGuardUser           setExcursionHasPolitica()     Sets the current record's "ExcursionHasPolitica" collection
 * @method sfGuardUser           setExcursionHasLugarInteres() Sets the current record's "ExcursionHasLugarInteres" collection
 * @method sfGuardUser           setExcursionHasInclusion()    Sets the current record's "ExcursionHasInclusion" collection
 * @method sfGuardUser           setExcursionHasRequisito()    Sets the current record's "ExcursionHasRequisito" collection
 * @method sfGuardUser           setExcursionPrecio()          Sets the current record's "ExcursionPrecio" collection
 * 
 * @package    hub-usmjesus
 * @subpackage model
 * @author     Jesus Salazar - usmjesus@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('identificacion', 'string', 50, array(
             'type' => 'string',
             'notnull' => 'tru',
             'length' => 50,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('direcion', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('telefono_principal', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('sexo', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('tipo_personal_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('edo_civil', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('nacionalidad', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('ocupacion', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 50,
             ));
        $this->hasColumn('titulo', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 50,
             ));
        $this->hasColumn('grado_instruccion', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 50,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('alerta', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('observacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'notnull' => false,
             'length' => '',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('TipoPersonal', array(
             'local' => 'tipo_personal_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardForgotPassword as ForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Pais', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('RangoEdad', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoTarifa', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoTarifaPrecio', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoCliente', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Proveedor', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ProveedorSucursal', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('GaleriaProveedor', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('GaleriaDescuento', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ProveedorDescuento', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ProveedorRede', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ProveedorPago', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Categoria', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Ciudad', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Pago', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Provincia', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Ubicacion', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('GaleriaUbicacion', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Rede', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Campo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('CampoDescuento', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('CategoriaFaq', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('DetalleFaq', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('EmpresaSeccion', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoVuelo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoMotivo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoLona', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoRestriciones', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoRecomendaciones', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Globo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('MantenimientoGlobo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ProveedorVuelo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VueloRestriciones', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VueloRecomendaciones', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VueloServicio', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VueloHospedaje', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Cliente', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VueloCliente', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Marca', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Quemador', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('MantenimientoQuemador', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoCanastilla', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Canastilla', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('MantenimientoCanastilla', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Tanque', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('MantenimientoTanque', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoHabitacion', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TipoCama', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Hospedaje', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('HospedajeHabitacion', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('GaleriaHospedaje', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('HospedajeRede', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('HospedajePago', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Vehiculo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoHasPolitica', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoHasSeguro', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoHasAdicional', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoCategoria', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoTipoReproductor', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoMarca', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoMarcaModelo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoTipo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoTipoTransmision', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoPrecio', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoAdicional', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoPolitica', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('VehiculoSeguro', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Seguro', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SeguroTipo', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SeguroPlan', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SeguroBeneficio', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SeguroHasBeneficio', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SeguroPrecio', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Excursion', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionAdicional', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionPolitica', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionLugarInteres', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionRequisito', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionIncluible', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionHasAdicional', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionHasPolitica', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionHasLugarInteres', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionHasInclusion', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionHasRequisito', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ExcursionPrecio', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}