<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/03/21 23:29:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=agenciard',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
